# Generated by Django 5.0.6 on 2024-05-08 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendanutri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='data_consulta',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 4, 35, 6, 568241, tzinfo=datetime.timezone.utc)),
        ),
    ]
