# Generated by Django 5.0.6 on 2024-05-08 19:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendanutri', '0002_paciente_data_consulta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='data_consulta',
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateTimeField(default=datetime.datetime(2024, 5, 8, 19, 2, 48, 38735, tzinfo=datetime.timezone.utc))),
                ('data_retorno', models.DateTimeField(default=datetime.datetime(2024, 5, 8, 19, 2, 48, 38735, tzinfo=datetime.timezone.utc))),
                ('data_reagendamento', models.DateTimeField(default=datetime.datetime(2024, 5, 8, 19, 2, 48, 38735, tzinfo=datetime.timezone.utc))),
                ('data_criacao', models.DateTimeField(default=datetime.datetime(2024, 5, 8, 19, 2, 48, 38735, tzinfo=datetime.timezone.utc))),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendanutri.paciente')),
            ],
        ),
    ]
