# Generated by Django 5.0.6 on 2024-05-09 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendanutri', '0003_remove_paciente_data_consulta_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='data_consulta',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 15, 39, 50, 746126, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='data_reagendamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='data_retorno',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
