# Generated by Django 5.0.6 on 2024-05-09 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendanutri', '0004_alter_agenda_data_consulta_alter_agenda_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 9, 15, 51, 2, 174238, tzinfo=datetime.timezone.utc)),
        ),
    ]
