# Generated by Django 5.0.6 on 2024-05-27 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendanutri', '0005_alter_agenda_data_criacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='data_reagendamento',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='data_retorno',
        ),
        migrations.AddField(
            model_name='agenda',
            name='horario_consulta',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='data_consulta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 19, 15, 0, 52872, tzinfo=datetime.timezone.utc)),
        ),
    ]
