# Generated by Django 5.0.6 on 2024-05-27 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendanutri', '0006_remove_agenda_data_reagendamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='data_consulta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 19, 51, 23, 711363, tzinfo=datetime.timezone.utc)),
        ),
    ]
